# Generated by Django 4.1.5 on 2023-01-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=5000)),
                ('category', models.CharField(default='', max_length=5000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('Internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internship')),
            ],
        ),
        migrations.CreateModel(
            name='ProLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProLang', models.CharField(max_length=100)),
                ('Internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internship')),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('Internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internship.internship')),
            ],
        ),
    ]
