# Generated by Django 4.1.5 on 2023-01-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='closing_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='open_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
    ]
