# Generated by Django 4.1.5 on 2023-01-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_det', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
